version: '3'
services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clothes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - proxy
      - internal
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3306:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - proxy
      - internal
  # redis
  # redis:
  #   image: redis:7.0.0-alpine
  #   ports:
  #     - "6379"
  #   networks:
  #     - proxy
  #     - internal
networks:
  proxy:
    external:
      name: proxy
  internal:
    driver: bridge
volumes:
  db_data:
